# fly.toml app configuration file generated for envguard-app on 2026-05-10T11:05:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'envguard-app'
primary_region = 'iad'

[build]
  dockerfile = 'packages/app/Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 200
    soft_limit = 100

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
