const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const SCHEMA_FILENAME = '.env.schema';

/**
 * Parse a .env.schema file from disk.
 *
 * Returns a map of VAR_NAME → { description, required, example }
 * Returns an empty object if the file does not exist.
 *
 * @param {string} [dir]  — directory containing .env.schema (default: cwd)
 * @returns {{ [varName: string]: SchemaEntry }}
 */
function readSchema(dir = process.cwd()) {
  const schemaPath = path.join(dir, SCHEMA_FILENAME);
  if (!fs.existsSync(schemaPath)) return {};

  const raw = fs.readFileSync(schemaPath, 'utf8');
  return parseSchemaYaml(raw);
}

/**
 * Parse a .env.schema YAML string directly (useful for GitHub App — schema fetched via API).
 *
 * @param {string} yamlString
 * @returns {{ [varName: string]: SchemaEntry }}
 */
function parseSchemaYaml(yamlString) {
  if (!yamlString || !yamlString.trim()) return {};

  let parsed;
  try {
    parsed = yaml.load(yamlString);
  } catch (err) {
    throw new Error(`Invalid .env.schema YAML: ${err.message}`);
  }

  if (parsed === null || parsed === undefined) return {};
  if (typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new Error('.env.schema must be a YAML mapping (key: value pairs at the top level)');
  }

  const schema = {};
  for (const [key, value] of Object.entries(parsed)) {
    if (!isValidVarName(key)) {
      // Warn but don't fail — allows lowercase or mixed-case keys like port
      // Teams might use non-standard naming in early adoption
    }
    schema[key] = normalizeEntry(value);
  }
  return schema;
}

/**
 * Write a new .env.schema file to disk.
 * Preserves existing entries if the file already exists — only adds new keys.
 *
 * @param {string[]} varNames — list of variable names to add (deduplicated)
 * @param {string} [dir] — directory to write to (default: cwd)
 * @param {{ overwrite?: boolean }} [options]
 * @returns {{ added: string[], skipped: string[], path: string }}
 */
function writeSchema(varNames, dir = process.cwd(), options = {}) {
  const schemaPath = path.join(dir, SCHEMA_FILENAME);
  const existing = readSchema(dir);

  const added = [];
  const skipped = [];

  const schema = { ...existing };

  for (const name of deduplicate(varNames)) {
    if (!options.overwrite && existing[name]) {
      skipped.push(name);
      continue;
    }
    schema[name] = {
      description: '',
      required: true,
      example: '',
    };
    added.push(name);
  }

  const yamlStr = buildSchemaYaml(schema);
  fs.writeFileSync(schemaPath, yamlStr, 'utf8');

  return { added, skipped, path: schemaPath };
}

/**
 * Check which variable names from a list are NOT in the schema.
 *
 * @param {string[]} varNames
 * @param {{ [varName: string]: SchemaEntry }} schema
 * @returns {string[]} — names missing from schema
 */
function findUndocumented(varNames, schema) {
  return varNames.filter(name => !schema[name]);
}

/**
 * Validate schema entries — finds vars marked required: true but with empty descriptions.
 *
 * @param {{ [varName: string]: SchemaEntry }} schema
 * @returns {{ varName: string, issue: string }[]}
 */
function validateSchema(schema) {
  const issues = [];
  for (const [varName, entry] of Object.entries(schema)) {
    if (!entry.description || !entry.description.trim()) {
      issues.push({ varName, issue: 'missing description' });
    }
    if (!entry.example && entry.required !== false) {
      issues.push({ varName, issue: 'missing example (recommended for required vars)' });
    }
  }
  return issues;
}

// ─── Internal helpers ──────────────────────────────────────────────────────────

function normalizeEntry(value) {
  if (value === null || value === undefined) {
    return { description: '', required: true, example: '' };
  }
  if (typeof value === 'string') {
    // Shorthand: VAR_NAME: "description string"
    return { description: value, required: true, example: '' };
  }
  return {
    description: String(value.description || ''),
    required: value.required !== false,  // default to true
    example: value.example !== undefined ? String(value.example) : '',
  };
}

/**
 * Build a well-formatted YAML string from a schema object.
 * Produces human-readable output — each entry as a block with comments.
 */
function buildSchemaYaml(schema) {
  const keys = Object.keys(schema).sort();
  if (keys.length === 0) return '';

  const lines = [
    '# .env.schema — generated by EnvGuard',
    '# Run `npx envguard check` to validate your codebase against this file.',
    '# Docs: https://github.com/envguard/envguard',
    '',
  ];

  for (const key of keys) {
    const entry = schema[key];
    lines.push(`${key}:`);
    lines.push(`  description: ${yamlValue(entry.description)}`);
    lines.push(`  required: ${entry.required !== false}`);
    if (entry.example) {
      lines.push(`  example: ${yamlValue(String(entry.example))}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function yamlValue(str) {
  if (!str) return '""';
  // Quote if contains special YAML characters
  if (/[:#\[\]{},&*?|<>=!%@`]/.test(str) || str.includes('\n')) {
    return JSON.stringify(str);
  }
  return str;
}

function isValidVarName(name) {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(name);
}

function deduplicate(arr) {
  return [...new Set(arr)];
}

module.exports = {
  readSchema,
  parseSchemaYaml,
  writeSchema,
  findUndocumented,
  validateSchema,
  SCHEMA_FILENAME,
};
